library(rjson)
setwd( "/Users/Isaac_Zhang/Research/MCMC/simulation_seed/EXP_DIM_3/exp_k2/")
library(ggplot2)
library(mcmcse)
gbsbetalist <- fromJSON(file = "__0_GBS_alpha0.5")
mhbetalist <- fromJSON(file = "__0_MH_alpha0.5")
  p <- ecdf(mhbetalist)
  p(0.0)
  #p2 <- ecdf(omhbetalist)
  #p2(0.0)
  p3 <- ecdf(gbsbetalist)
  p3(0.0)
  plot(p, verticals=TRUE, do.points=FALSE, col = 'blue')
  plot(p3, verticals=TRUE, do.points=FALSE, add=TRUE)
  ######
  show(ess(mhbetalist)) 
  show("gbsess")
  show(ess(gbsbetalist))
